version: "3.9" # Optionnel mais recommandé

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: react_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8002:80
    networks:
      - app-network

  api:
    build:
      context: ./Express-Project
      dockerfile: Dockerfile
    image: express-project
    container_name: api
    ports:
      - 8001:8001
    volumes:
      - ./Express-Project:/app
    networks:
      - app-network

  front:
    build:
      context: ./Vite-Project
      dockerfile: Dockerfile
    image: vite-project
    container_name: front
    ports:
      - 8000:8000
    volumes:
      - ./Vite-Project:/app
    networks:
      - app-network

  server-web:
    image: nginx:latest
    container_name: server-web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - api
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
